ProyectoEjemploMod10/Models/ContextoDeDatos.cs
using Microsoft.EntityFrameworkCore;

namespace ProyectoEjemploMod10.Models
{
    public class ContextoDeDatos : DbContext
    {

        public ContextoDeDatos(DbContextOptions opciones) : base(opciones)
            {
            }
        public DbSet<Departamento> Departamentos { get; set; }

    }

}

ProyectoEjemploMod10/Models/Departamento.cs
using System.ComponentModel.DataAnnotations;

namespace ProyectoEjemploMod10.Models
{
    public class Departamento
    {
        [Key]
        public int Id { get;set; }

        [Required(ErrorMessage = "El nombe es requerido")]
        [MaxLength(50, ErrorMessage = "Maximo 50 caracteres")]
        [Display(Name = "Nombre del departamento")]

        public string Nombre { get; set; } = string.Empty;
    }

}

ProyectoEjemploMod10/Models/ErrorViewModel.cs
namespace ProyectoEjemploMod10.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoEjemploMod10/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoEjemploMod10.Models;
using X.PagedList;

namespace ProyectoEjemploMod10.Controllers
{
    public class DepartamentoController : Controller
    {
        private readonly ContextoDeDatos contexto;

        //Inyeccion del conecto de datos
        public DepartamentoController(ContextoDeDatos contexto)
        {
            this.contexto = contexto;
        }

        //Accion que muestra la pagina principal para adminstrar Departamentos
        public async Task <IActionResult> Index(int? page)
        {
            int pageSize = 1; // número de registros por pagina 
            int pageNumber = (page ?? 3); // número de pagina actual,  predeterminado 1 si entra vacio

            var departamentos = await contexto.Departamentos.OrderBy(d=> d.Nombre).ToPagedListAsync(pageNumber, pageSize); 

            return View(departamentos);
        }

        //Accion que muestra los detalles de los registros
        public async Task<IActionResult> Details(int id){
            var departamento= await contexto.Departamentos.
                 SingleOrDefaultAsync(d => d.Id == id);
                 return View(departamento);
        }


        //accion que muestra el formulario para crear un nuevo departamento
        public IActionResult Create()
        {
            return  View();
        }

        //accion que recibe los datos del formulario para guardarlos ene la bd
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Departamento departamento){
            if (ModelState.IsValid)
            {
                contexto.Departamentos.Add(departamento);
                await contexto.SaveChangesAsync();
                return  RedirectToAction("Index");
            } else {
                return View(departamento);
            }
        }
    }
}

ProyectoEjemploMod10/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoEjemploMod10.Models;
using System.Diagnostics;

namespace ProyectoEjemploMod10.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoEjemploMod10/Views/Departamento/Create.cshtml
@model ProyectoEjemploMod10.Models.Departamento

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-outline-primary">Regresar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProyectoEjemploMod10/Views/Departamento/Details.cshtml
@model ProyectoEjemploMod10.Models.Departamento

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a  class="btn btn-success" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a   asp-action="Index"  class="btn btn-outline-primary ">Regresar</a>
</div>

ProyectoEjemploMod10/Views/Departamento/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core

 @model IPagedList<ProyectoEjemploMod10.Models.Departamento>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Nuevo Deparamento</a>
</p>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Nombre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
               <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
               <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Details</a> |
               <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>

        </tr>
}
    </tbody>
</table>

<div class="text-center">

    @Html.PagedListPager(Model, page => Url.Action("Index", new{page}), 
    new PagedListRenderOptions{
        LiElementClasses = new string[] {"page-item"},
        PageClasses = new string[] {"page-link"}
    });

</div>

ProyectoEjemploMod10/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoEjemploMod10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoEjemploMod10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoEjemploMod10.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoEjemploMod10</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="Index">Departamento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProyectoEjemploMod10 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>